version: '3.9'

services:
  fail2ban:
    image: crazymax/fail2ban:0.11.2
    container_name: fail2ban
    network_mode: 'host'
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - '/srv/fail2ban/data:/data'
      - '/var/log:/var/log:ro'
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_ACTION=%(action_mwl)s
      - F2B_DEST_EMAIL=${F2B_DEST_EMAIL}
      - SSMTP_HOST=mail.infomaniak.com
      - SSMTP_PORT=587
      - SSMTP_USER=${F2B_USER}
      - SSMTP_PASSWORD=${F2B_PASSWORD}
      - SSMTP_HOSTNAME=${F2B_HOSTNAME}
      - SSMTP_TLS=NO
      - SSMTP_STARTTLS=YES
  manager:
    image: jc21/nginx-proxy-manager:2.9.18
    container_name: nginx-proxy-manager
    environment:
      TZ: 'Europe/Paris'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /srv/nginx-proxy-manager/data:/data
      - /var/log/nginx-proxy-manager:/data/logs/
      - /srv/nginx-proxy-manager/data/letsencrypt:/etc/letsencrypt
    networks:
      - reverse-proxy-nw
  main:
    image: lgdweb/nginx-test:latest
    container_name: nginx-main
    networks:
      - reverse-proxy-nw
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  agent:
    image: portainer/agent:2.14.2-alpine
    container_name: portainer-agent
    restart: unless-stopped
    networks:
      - portainer-default
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  server:
    image: portainer/portainer-ce:2.14.2-alpine
    container_name: portainer-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - portainer-default
      - reverse-proxy-nw
    ports:
      - '9443:9443'
      - '9000:9000'
      - '8000:8000'
    volumes:
      - /srv/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  portainer-default:
    attachable: true
  reverse-proxy-nw:
    external: true
